server:
  port: 10000
  max-http-header-size: 10000000
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 80
      idle-timeout: 500
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

# 配置 mybatis
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.wzp.oauth2.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置(全局)
custom-config:
  withClient: wzp-auth
  secret: wzp1
  resourceId: wzp1
  defaultPassword: e10adc3949ba59abbe56e057f20f883e
  ipData: G:\IpData\ip2region.db
  publicNetWork: http://ip.chinaz.com


